const movies = [
    {
        id:'1',
        title:'Justice League (2017)',
        description:"In the 2017 film 'Justice League', directed by Zack Snyder, the world faces a grave threat following Superman's death. Bruce Wayne, aka Batman, and Diana Prince, known as Wonder Woman, unite a team of metahumans - including Aquaman, Cyborg, and the Flash - to combat the impending invasion of Steppenwolf and his army of Parademons. Their mission is to locate three Mother Boxes, ancient artifacts that, when combined, have the power to reshape reality. As the newly formed Justice League battles Steppenwolf, they grapple with their own internal conflicts and the weight of their responsibilities. Despite initial setbacks and personal doubts, the heroes must learn to work together to save Earth from destruction. With action-packed sequences, spectacular visual effects, and a blend of humor and heart, 'Justice League' is a thrilling adventure that showcases the power of teamwork and the resilience of the human spirit in the face of adversity.",
        img:'https://ntvb.tmsimg.com/assets/p12543991_v_h8_aa.jpg?w=1280&h=720',
    },
    {
        id:'2',
        title:'Justice League: The New Frontier (2008)',
        description:"Justice League: The New Frontier: is a 2008 animated film adapted from the DC Comics limited series written by Darwyn Cooke. Set in the 1950s during the Cold War era, the story explores the formation of the Justice League amidst a world on the brink of chaos. The narrative intertwines the origin stories of various iconic DC superheroes, including Batman, Superman, Wonder Woman, Green Lantern, and the Flash, against the backdrop of societal and political upheaval. As the threat of nuclear war looms, these heroes are forced to confront their own demons and differences while also battling against a common enemy, the monstrous entity known as the Centre, which seeks to destroy humanity. Led by the enigmatic Martian Manhunter, the heroes must overcome their individual struggles and band together to save the world from impending doom. The film delves into themes of heroism, sacrifice, and the struggle for justice in a world plagued by fear and intolerance. It portrays the superheroes not only as powerful beings but also as complex individuals grappling with their place in society and their moral responsibilities.With its retro art style and compelling storyline, Justice League: The New Frontier offers a fresh perspective on the classic superhero team-up, blending action-packed sequences with thought-provoking commentary on the human condition and the nature of heroism.",
        img:'https://m.media-amazon.com/images/S/pv-target-images/dea75ba6807494aa9225a65456069eb2a75be4d2eee217cdf2029326093a2298.jpg',
    },
    {
        id:'3',
        title:'Justice League: Crisis on Two Earths (2010)',
        description:"Justice League: Crisis on Two Earths is a 2010 animated film that takes viewers on a thrilling journey through parallel universes and moral dilemmas. The story follows the Justice League as they encounter their counterparts from an alternate reality, the Crime Syndicate, led by the ruthless Ultraman. When the Crime Syndicate threatens not only their own world but also the safety of Earth Prime, the Justice League must put aside their differences and join forces to stop them. The film explores themes of duality, morality, and the consequences of power. As the Justice League grapples with their counterparts, they are forced to confront the darker aspects of their own natures and question the nature of heroism itself. The dynamic between the heroic Justice League and the villainous Crime Syndicate adds layers of complexity to the narrative, highlighting the shades of grey that exist within the DC Universe. Filled with action-packed sequences, intricate plot twists, and thought-provoking themes, Justice League: Crisis on Two Earths offers an engaging and entertaining ride for both fans of the comics and newcomers alike. It challenges audiences to ponder the choices we make and the impact they have on the world around us, making it a standout entry in the realm of animated superhero films.",
        img:'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8013559_v_h9_af.jpg',
    },
    {
        id:'4',
        title:'Justice League: Doom (2012)',
        description:"Justice League: Doom is a 2012 animated film that explores the consequences of a nefarious plot to dismantle the Justice League from within. When the team's archenemy, Vandal Savage, obtains contingency plans devised by Batman to neutralize each member of the Justice League, he enlists a group of supervillains to execute his scheme. As the Justice League faces off against their own weaknesses and vulnerabilities, they must overcome personal doubts and conflicts to prevent Savage's sinister plan from succeeding. The film delves into themes of trust, loyalty, and the burden of responsibility. It raises questions about the ethics of preemptive measures and the fine line between protection and control. Through intense action sequences and character-driven drama, Justice League: Doom showcases the resilience and unity of the Justice League as they confront their greatest challenge yet. With its compelling storyline and dynamic animation, the film offers a captivating exploration of heroism and the challenges faced by those who strive to protect the greater good. It serves as a reminder that even the mightiest heroes are not immune to the dangers of hubris and betrayal, making it a standout addition to the Justice League animated canon.",
        img:'https://facts.net/wp-content/uploads/2023/10/45-facts-about-the-movie-justice-league-doom-1698221178.jpg',
    },
    {
        id:'5',
        title:'Justice League: The Flashpoint Paradox (2013)',
        description:"Justice League: The Flashpoint Paradox (2013) presents a gripping alternate reality where the Flash, Barry Allen, inadvertently alters the timeline, leading to catastrophic consequences. In this altered world, the Justice League doesn't exist, and familiar heroes have drastically different roles and identities. Barry must navigate this fractured reality to restore the timeline, facing formidable adversaries and making difficult choices along the way. The film delves into themes of sacrifice, redemption, and the ripple effects of one's actions. As Barry races against time to set things right, he grapples with the personal toll of his decisions and the weight of responsibility. With its intense action sequences, complex narrative, and emotional depth, Justice League: The Flashpoint Paradox offers a thought-provoking exploration of the nature of heroism and the consequences of altering reality. It challenges audiences to consider the power of choice and the importance of understanding the far-reaching implications of one's actions. Through its riveting storytelling and dynamic animation, the film stands as a standout entry in the Justice League animated universe.",
        img:'https://streamondemandathome.com/wp-content/uploads/2022/06/Flashpoint_Paradox.jpg',
    },
    {
        id:'6',
        title:'JLA Adventures: Trapped in Time (2014)',
        description:"JLA Adventures: Trapped in Time (2014) follows the Justice League as they face a new threat when the Time Trapper alters history to prevent the League's formation. With the fabric of time unraveling, the League must join forces with two teenage heroes, Karate Kid and Dawnstar, to restore the timeline and defeat the Time Trapper. As they journey through different eras, battling iconic villains and overcoming challenges, the League learns the value of teamwork and the importance of standing up for justice across generations. The film explores themes of friendship, courage, and the resilience of the human spirit in the face of adversity. Through its action-packed sequences and heartwarming moments, JLA Adventures: Trapped in Time delivers an entertaining and uplifting adventure for audiences of all ages. With its dynamic animation and engaging storyline, the film captures the spirit of heroism and camaraderie that defines the Justice League, making it a memorable addition to the DC animated universe.",
        img:'https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/32ef0634-962c-41bb-8861-023acc45f817/60e4c0d515056f7f4d4274f820ac972cb6b940b1.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom',
    },
    {
        id:'7',
        title:'Justice League: War (2014)',
        description:"Justice League: War (2014) introduces audiences to a reimagined origin story of the Justice League as they come together to defend Earth against an otherworldly invasion led by Darkseid, the tyrannical ruler of Apokolips. As the world faces its greatest threat yet, Batman, Superman, Wonder Woman, the Flash, Green Lantern, Cyborg, and Shazam must put aside their differences and unite as a team to combat Darkseid's forces. The film explores themes of teamwork, trust, and the struggle to find common ground amidst diverse personalities and powers. Through intense battles and personal challenges, the members of the Justice League learn to work together and harness their unique abilities for the greater good. Justice League: War captivates audiences with its fast-paced action, dynamic animation, and witty dialogue, offering a fresh and exhilarating take on the iconic superhero team. With its epic scope and compelling character dynamics, the film serves as a thrilling introduction to the Justice League for both longtime fans and newcomers alike. It sets the stage for future adventures while celebrating the enduring legacy of these legendary heroes in the DC Universe.",
        img:'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10460755_v_h9_ab.jpg',
    },
    {
        id:'8',
        title:'Justice League: Throne of Atlantis (2015)',
        description:"Justice League: Throne of Atlantis (2015) plunges viewers into an underwater adventure as the Justice League faces a new threat from the depths of the ocean. When the kingdom of Atlantis is thrown into turmoil following the death of its king, Arthur Curry, also known as Aquaman, reluctantly joins forces with the League to prevent a war between Atlantis and the surface world. As they uncover dark secrets and face formidable adversaries, including the power-hungry Ocean Master, the League must navigate treacherous waters to restore peace. The film explores themes of identity, family, and the clash between tradition and progress. Through stunning underwater visuals and high-stakes action sequences, Justice League: Throne of Atlantis immerses audiences in a world of intrigue and danger beneath the waves. With its dynamic character dynamics and heartfelt moments, the film offers a compelling exploration of Arthur Curry's journey to embrace his destiny as the rightful ruler of Atlantis and a hero to both land and sea. Justice League: Throne of Atlantis stands as a thrilling addition to the DC animated universe, delivering a captivating blend of superhero spectacle and emotional depth. It celebrates the enduring legacy of Aquaman and his role within the Justice League while setting the stage for further adventures in the vast oceanic realm.",
        img:'https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/524621cb-7e02-4305-9a3c-ac32e38cca10/2bb0618cb5c70f7a4111d002fa6e072229084504.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom',
    },
    {
        id:'9',
        title:'Justice League: Gods and Monsters (2015)',
        description:"Justice League: Gods and Monsters (2015) presents an alternate reality where familiar heroes, Superman, Batman, and Wonder Woman, are reimagined as darker and more morally ambiguous versions of themselves. In this world, Superman is the son of General Zod, Batman is Kirk Langstrom, a vampiric scientist, and Wonder Woman is Bekka, a New God from Apokolips. When a series of murders rocks the world, the Justice League must confront their own identities and uncover the truth behind the killings. As they delve deeper into the mystery, they face off against powerful adversaries and grapple with the consequences of their actions. The film explores themes of power, redemption, and the nature of heroism in a world where the line between good and evil is blurred. Through its gritty animation and thought-provoking narrative, Justice League: Gods and Monsters offers a compelling exploration of familiar characters from a fresh perspective. It challenges audiences to reconsider their preconceptions of these iconic heroes while delivering thrilling action and complex character dynamics ",
        img:'https://lamplightreview.com/wp-content/uploads/2015/07/Justice_League_Gods_Monsters_02.jpg',
    },
    {
        id:'10',
        title:'Justice League vs. Teen Titans (2016)',
        description:"Justice League vs. Teen Titans (2016) pits the Justice League against a new threat when the demon Trigon seeks to conquer the world through his daughter, Raven. As Trigon's dark influence spreads, the Justice League's newest member, Damian Wayne, struggles to fit in with the team. When his reckless behavior leads to a confrontation with the Teen Titans, led by Starfire, the two teams must put aside their differences and unite to stop Trigon's sinister plans. Along the way, they face inner demons and forge unlikely alliances to save the world from destruction. The film delves into themes of family, redemption, and the power of teamwork. Through intense battles and personal struggles, the characters must confront their pasts and overcome their own weaknesses to stand together against the forces of evil. Justice League vs. Teen Titans delivers a thrilling blend of action, humor, and heart, offering fans an exciting crossover between two beloved superhero teams. It celebrates the legacy of both the Justice League and the Teen Titans while introducing new dynamics and relationships that will leave audiences eager for more adventures.",
        img:'https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/059674d4-dbe5-498f-9d40-0d3c11b6b428/8a1ad0a28d92658f0a05d5f08f4d5cb23c9a9145.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom',
    },
    {
        id:'11',
        title:'Justice League Dark (2017)',
        description:"Justice League Dark (2017) delves into the supernatural realm as a series of disturbing events plague the world, stemming from mystical forces beyond the comprehension of the Justice League. Batman recruits a team of occult experts, including John Constantine, Zatanna, Deadman, and Swamp Thing, to investigate and combat the growing supernatural threats. As they uncover a plot orchestrated by the demon lord, Destiny, to unleash chaos upon the world, the team must navigate treacherous dimensions and confront their own inner demons. Along the way, they forge uneasy alliances and grapple with the moral complexities of wielding dark magic in the name of justice. The film explores themes of redemption, sacrifice, and the blurred line between good and evil in a world where the supernatural lurks in the shadows. Through its atmospheric animation and captivating storyline, Justice League Dark offers a thrilling and mystical adventure that showcases the darker side of the DC Universe. It celebrates the diverse cast of characters and their unique abilities while delivering an engaging and thought-provoking tale of magic and mayhem.",
        img:'https://d3dfsf9oc1ojzp.cloudfront.net/original/4X/7/3/b/73b08b82c41c646a8e21866f0998ecf5472ce7df.jpeg',
    },
    {
        id:'12',
        title:'Justice League Dark: Apokolips War (2020)',
        description:"Justice League Dark: Apokolips War (2020) marks the culmination of the DC Animated Movie Universe as the Justice League faces their greatest challenge yet against the tyrannical rule of Darkseid. When the villainous ruler of Apokolips launches a devastating assault on Earth, the Justice League and their allies must rally together for one final stand to save humanity from annihilation. With the fate of the universe hanging in the balance, sacrifices must be made, alliances will be tested, and heroes will fall. As the battle rages on, the Justice League Dark, led by John Constantine, joins forces with the remaining heroes to confront Darkseid and his legions of Parademons. The film explores themes of redemption, resilience, and the enduring power of hope in the face of overwhelming odds. Through its epic scope, intense action sequences, and emotional depth, Justice League Dark: Apokolips War delivers a thrilling conclusion to the DC Animated Movie Universe, leaving audiences on the edge of their seats until the very end.",
        img:'https://i.redd.it/cqg8svip4ex41.jpg',
    },
    {
        id:'13',
        title:'Injustice (2021)',
        description:"Injustice (2021) presents an alternate reality where Superman, driven to extreme measures by personal tragedy, establishes a totalitarian regime to impose his vision of peace upon the world. After the Joker's actions result in the death of Lois Lane and the destruction of Metropolis, Superman becomes a tyrant, ruling with an iron fist and eliminating anyone he perceives as a threat. Batman and a group of rebels, including familiar faces from the DC Universe, oppose Superman's regime, sparking a bitter conflict that threatens to tear the world apart. As the battle between justice and tyranny escalates, alliances are formed and loyalties are tested. The film delves into themes of power, corruption, and the consequences of unchecked authority. Through its gripping storyline and dynamic animation, Injustice offers a thought-provoking exploration of morality and the choices that define us. It challenges audiences to consider the limits of power and the importance of standing up for what is right, even in the face of overwhelming odds.",
        img:'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p20402128_v_h8_ae.jpg',
    },
    {
        id:'14',
        title:'Justice League: Warworld (2023)',
        description:"Justice League: Warworld (2023) thrusts the Justice League into their most perilous mission yet as they confront the tyrannical ruler of Warworld, Mongul. When Mongul threatens Earth with destruction unless the Justice League competes in gladiatorial combat on his planet, the heroes must navigate a deadly arena and face off against formidable opponents to save their world. With tensions rising and lives hanging in the balance, the Justice League must put aside their differences and unite as a team to overcome the seemingly insurmountable challenges ahead. As the battles rage on, personal sacrifices are made, and unexpected alliances are formed, the fate of Earth hangs in the balance. The film explores themes of teamwork, courage, and the resilience of the human spirit in the face of overwhelming odds. Through its exhilarating action sequences and heart-pounding drama, Justice League: Warworld delivers an epic adventure that celebrates the enduring legacy of the Justice League while showcasing the strength and determination of Earth's mightiest heroes.",
        img:'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p24627965_v_h8_aa.jpg',
    },
    {
        id:'13',
        title:'Justice League: Crisis on Infinite Earths – Part One (2024)',
        description:"Justice League: Crisis on Infinite Earths – Part One (2024) plunges viewers into a multiverse-spanning crisis as the fabric of reality itself is threatened by the malevolent Anti-Monitor. With parallel worlds colliding and entire universes on the brink of destruction, the Justice League must assemble an unprecedented alliance of heroes from across the multiverse to confront this cosmic threat. Led by Superman, Batman, Wonder Woman, and other iconic heroes, the League races against time to prevent the total annihilation of existence. As they battle against the Anti-Monitor's forces and grapple with the enormity of the challenge before them, the heroes face personal sacrifices and unexpected revelations that will test their resolve like never before. The fate of all existence hangs in the balance as the Justice League and their allies embark on an epic quest to save the multiverse from ultimate destruction. Through its epic scope, intense action sequences, and dramatic storytelling, Justice League: Crisis on Infinite Earths – Part One delivers a thrilling and emotionally resonant tale that sets the stage for a universe-shattering showdown in the next installment.",
        img:'https://www.comingsoon.net/wp-content/uploads/sites/3/2024/01/Justice-League-Crisis-on-Infinite-Earths-Part-1.jpg',
    },
];

module.exports = movies