const tv = [
    {
        id:1,
        title: 'Adventures of Superman (1952 - 1958)',
        img:'https://m.media-amazon.com/images/M/MV5BZmYwMzY4OWMtZmYxMC00M2VmLWFlZDgtMWEyY2IzNDdjNWRmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg',
        description: '"Adventures of Superman" was a groundbreaking television series that aired from 1952 to 1958. Starring George Reeves as the iconic superhero, the show followed Supermans heroic exploits in Metropolis, battling villains like Lex Luthor and protecting the innocent. Focused on themes of justice and morality, it captivated audiences with its thrilling action sequences and moral lessons, leaving a lasting legacy in pop culture. ',
    },
    {
        id:2,
        title: 'Batman (1966 - 1968)',
        img:'',
        description: '"Batman" (1966-1968) is a cult classic TV series starring Adam West as the iconic Dark Knight and Burt Ward as his sidekick, Robin. Known for its campy humor, colorful visuals, and catchy theme song, the show depicted Batman and Robins crime-fighting adventures in Gotham City as they battled a rogues gallery of villains, including the Joker, Penguin, and Catwoman.',
    },
    {
        id:3,
        title: 'SuperFriends (1973)',
        img:'',
        description: '"SuperFriends" (1973) is an animated series that unites iconic DC superheroes like Superman, Batman, Wonder Woman, and others in their mission to protect Earth from supervillains and global threats. Aimed at younger audiences, the show combines action-packed adventures with moral lessons, emphasizing teamwork, friendship, and the importance of using powers for good. It became a beloved part of pop culture, inspiring generations of fans.',
    },
    {
        id:4,
        title: 'Wonder Woman (1975-1979)',
        img:'',
        description: '"Wonder Woman" (1975-1979) stars Lynda Carter as Diana Prince, the Amazonian princess known as Wonder Woman, who fights for justice during World War II and in the modern world. With her iconic costume and lasso of truth, she battles villains while promoting themes of compassion, equality, and strength. The series became a cultural phenomenon, showcasing a powerful female superhero on television.',
    },
    {
        id:5,
        title: 'The New Adventures of Batman (1977-1981)',
        img:'',
        description: '"The New Adventures of Batman" (1977-1981) brings the dynamic duo, Batman and Robin, back to the small screen in animated form. Voiced by Adam West and Burt Ward, the crime-fighting pair faces off against familiar foes like the Joker, Penguin, and Catwoman in Gotham City. With action-packed episodes and classic comic book storytelling, it captivated audiences of all ages.',
    },
    {
        id:6,
        title: 'Super Friends (1980 - 1984)',
        img:'',
        description: '"SuperFriends" (1984) continues the legacy of the beloved animated series, uniting iconic DC superheroes like Superman, Batman, Wonder Woman, and others. Together, they combat villains and protect the world from various threats. With its action-packed adventures and emphasis on teamwork and heroism, the show remains a favorite among fans of all ages, inspiring imagination and promoting positive values.',
    },
    {
        id:7,
        title: 'The Flash (1990 - 1991)',
        img:'',
        description: '"The Flash" (1990) brings the iconic DC superhero to television, following Barry Allen, portrayed by John Wesley Shipp, as he gains super speed and becomes the Scarlet Speedster. Fighting crime in Central City, he battles villains while struggling with personal challenges. With its thrilling action sequences and compelling storytelling, the series captivates audiences, leaving a lasting impact on superhero television.',
    },
    {
        id:8,
        title: 'Batman: The Animtated Series (1992 - 1995)',
        img:'',
        description: '"Batman: The Animated Series" (1992-1995) revolutionizes animated television with its dark, atmospheric portrayal of the Dark Knights adventures in Gotham City. With Kevin Conroy as Batman and Mark Hamill as the Joker, the series delves into complex storylines, iconic villains, and the psychological depths of its characters. Its innovative animation style and mature themes set a new standard for animated superhero storytelling. ',
    },
    {
        id:9,
        title: 'Superman: The Animated Series (1996-2000)',
        img:'',
        description: '"Superman: The Animated Series" (1996-2000) follows the iconic DC Comics superhero as he defends Metropolis from villains like Lex Luthor and Brainiac. Produced by Warner Bros. Animation, the show blends action, drama, and superheroics with sleek animation and compelling storytelling. It explores Supermans struggles balancing his dual identity as Clark Kent and his responsibilities as Earths protector. The series remains a beloved adaptation, praised for its faithful portrayal of the Man of Steels adventures.',
    },
    {
        id:10,
        title: 'The New Batman Adventures (1997 - 1999)',
        img:'',
        description: '',
    },
    {
        id:11,
        title: 'Batman Beyond (1999 - 2001)',
        img:'',
        description: '',
    },
    {
        id:12,
        title: 'Static Shock (2000 - 2004)',
        img:'',
        description: '',
    },
    {
        id:13,
        title: 'Justice League (2001 - 2004)',
        img:'',
        description: '',
    },
    {
        id:14,
        title: 'SmallVille (2001 - 2011)',
        img:'',
        description: '',
    },
    {
        id:15,
        title: 'Teen Titans (2003 - 2005)',
        img:'',
        description: '',
    },
    {
        id:16,
        title: 'The Batman (2004 - 2008)',
        img:'',
        description: '',
    },
    {
        id:17,
        title: 'Justice League Unlimited (2004 - 2006)',
        img:'',
        description: '',
    },
    {
        id:18,
        title: 'Auqaman (2006)',
        img:'',
        description: '',
    },
    {
        id:19,
        title: 'Batman: The Brave and the Bold (2008 - 2011)',
        img:'',
        description: '',
    },
    {
        id:20,
        title: 'Young Justice (2010 - Present)',
        img:'',
        description: '',
    },
    {
        id:21,
        title: 'Green Latern: The Animated Series (2011)',
        img:'',
        description: '',
    },
    {
        id:22,
        title: 'Arrow (2012 - 2020)',
        img:'',
        description: '',
    },
    {
        id:23,
        title: 'Teen Titans Go (2013 - Present)',
        img:'',
        description: '',
    },
    {
        id:24,
        title: 'Constantine (2014 - 2015)',
        img:'',
        description: '',
    },
    {
        id:25,
        title: 'The Flash (2014 - 2023)',
        img:'',
        description: '',
    },
    {
        id:26,
        title: 'Gotham (2014 - 2019)',
        img:'',
        description: '',
    },
    {
        id:27,
        title: 'Supergirl (2015 - 2021)',
        img:'',
        description: '',
    },
    {
        id:28,
        title: 'DC Legends of Tommorrow (2016 - 2022)',
        img:'',
        description: '',
    },
    {
        id:29,
        title: 'Justice League Action (2016 - 2018)',
        img:'',
        description: '',
    },
    {
        id:30,
        title: 'Black Lightning (2018 - 2021)',
        img:'',
        description: '',
    },
    {
        id:31,
        title: 'Krypton (2018 - 2019)',
        img:'',
        description: '',
    },
    {
        id:32,
        title: 'Titans (2018 - 2023)',
        img:'',
        description: '',
    },
    {
        id:33,
        title: 'Doom Patrol (2019 - 2023)',
        img:'',
        description: '',
    },
    {
        id:34,
        title: 'Lucifer (2016 - 2021)',
        img:'',
        description: '',
    },
    {
        id:35,
        title: 'Swamp Thing (2019)',
        img:'',
        description: '',
    },
    {
        id:36,
        title: 'Batwoman (2019 - 2022)',
        img:'',
        description: '',
    },
    {
        id:37,
        title: 'Watchmen (2019)',
        img:'',
        description: '',
    },
    {
        id:38,
        title: 'Harley Quinn (2019 - Present)',
        img:'',
        description: '',
    },
    {
        id:39,
        title: 'Pennyworth (2019 - 2023)',
        img:'',
        description: '',
    },
    {
        id:40,
        title: 'DCs Stargirl (2020 - 2022)',
        img:'',
        description: '',
    },
    {
        id:41,
        title: 'Superman and Lois (2021 - 2024)',
        img:'',
        description: '',
    },
    {
        id:42,
        title: 'Peacemaker (2022 - Present)',
        img:'',
        description: '',
    },
    {
        id:43,
        title: 'My Adventures with Superman (2023 - Present)',
        img:'',
        description: '',
    },
]

module.exports = tv;